### ISSUE TITLE
No updates

### ISSUE THREAD

**Issue by tonobo** [shokai/hubot-rss-reader#54]
I won't get any updates, on my feeds.

```yaml
  hubot:
    image: rocketchat/hubot-rocketchat
    environment:
      - ROCKETCHAT_URL=rocketchat:8065
      - ROCKETCHAT_ROOM=''
      - HUBOT_RSS_INTERVAL=60
      - ROCKETCHAT_USER=hubot
      - LISTEN_ON_ALL_PUBLIC=true
      - ROCKETCHAT_PASSWORD=<my super secret password>
      - BOT_NAME=hubot
      - EXTERNAL_SCRIPTS=hubot-help,hubot-rss-reader
    links:
      - rocketchat:rocketchat
    ports:
      - "127.0.0.1:3001:8080"
```
